fix:
  default:
    begin_string: FIX.4.4
    heartbeat_interval: 30
    reset_on_logon: true
    target_comp_id: EXCHANGE
    host: 127.0.0.1
  sessions:
    - key: f01
      port: 5003
      sender_comp_id: SESSION01
    - key: f02
      port: 5003
      sender_comp_id: SESSION02
    - key: f03
      port: 25000
      sender_comp_id: SESSION03

dropcopy:
  default:
    begin_string: FIX.4.2
    heartbeat_interval: 30
    reset_on_logon: true
    target_comp_id: EXCHANGE
    host: 127.0.0.1
  sessions:
    - key: d01
      host: 127.0.0.1
      port: 30688
      sender_comp_id: DROP01
      username: your_username
      password: your_password
